In [29]:
import pandas as pd
import keras
import numpy as np
from keras.models import Sequential
from keras.layers import Dense
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/Bhushan0130/Datasets/main/iris.csv')
df.head()

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [7]:
x = df.iloc[ :,:-1].values
y = df.iloc[ :,-1].values

### Encoding

In [12]:
lebel = LabelEncoder()
y1 = lebel.fit_transform(y)

### OnehotEncoding

In [15]:
Y = pd.get_dummies(y1).values
# Y

In [19]:
## Data Spliting
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split (x, Y, test_size = 0.20, random_state = 15)

In [21]:
model = Sequential()
model.add(Dense(4, input_shape = (4,) , activation = 'relu'))
model.add(Dense(3, activation = 'sigmoid'))

In [22]:
model.compile(optimizer = 'Adam', loss = 'categorical_crossentropy', metrics = ['accuracy'])

In [ ]:
model.fit()

In [24]:
model.fit(x_train, y_train, batch_size = 20, epochs= 150)

Epoch 1/150
6/6 [==============================] - 2s 3ms/step - loss: 2.8297 - accuracy: 0.3083
Epoch 2/150
6/6 [==============================] - 0s 3ms/step - loss: 2.6815 - accuracy: 0.3083
Epoch 3/150
6/6 [==============================] - 0s 3ms/step - loss: 2.5391 - accuracy: 0.3083
Epoch 4/150
6/6 [==============================] - 0s 3ms/step - loss: 2.3775 - accuracy: 0.3083
Epoch 5/150
6/6 [==============================] - 0s 3ms/step - loss: 2.2116 - accuracy: 0.3083
Epoch 6/150
6/6 [==============================] - 0s 3ms/step - loss: 2.0452 - accuracy: 0.3083
Epoch 7/150
6/6 [==============================] - 0s 3ms/step - loss: 1.8880 - accuracy: 0.3083
Epoch 8/150
6/6 [==============================] - 0s 3ms/step - loss: 1.7368 - accuracy: 0.3083
Epoch 9/150
6/6 [==============================] - 0s 3ms/step - loss: 1.6151 - accuracy: 0.3083
Epoch 10/150
6/6 [==============================] - 0s 3ms/step - loss: 1.4964 - accuracy: 0.3167
Epoch 11/150
6/6 [===========

In [25]:
y_pred = model.predict(x_test)

In [26]:
y_pred

array([[0.6415068 , 0.44131023, 0.3895004 ],
       [0.34941396, 0.645704  , 0.6170701 ],
       [0.3132465 , 0.69068664, 0.5815015 ],
       [0.6176004 , 0.47585288, 0.3848221 ],
       [0.642596  , 0.4547298 , 0.40065455],
       [0.30915815, 0.6835887 , 0.6005868 ],
       [0.12936747, 0.51972336, 0.9033983 ],
       [0.5100836 , 0.66226965, 0.43936285],
       [0.34966815, 0.5966126 , 0.63171387],
       [0.16735727, 0.6241901 , 0.80441296],
       [0.24171257, 0.6059181 , 0.7567704 ],
       [0.3703008 , 0.7298532 , 0.5239337 ],
       [0.38160267, 0.74836886, 0.5033969 ],
       [0.40397963, 0.7620337 , 0.43401575],
       [0.1705119 , 0.4813653 , 0.8793233 ],
       [0.61219305, 0.48358932, 0.38378307],
       [0.37547377, 0.702774  , 0.5191265 ],
       [0.10575342, 0.416877  , 0.9325485 ],
       [0.6222844 , 0.46912688, 0.38572755],
       [0.20055261, 0.7647548 , 0.6870533 ],
       [0.4040216 , 0.7190101 , 0.5075275 ],
       [0.63960195, 0.44408095, 0.38912216],
       [0.

In [27]:
y_test

array([[1, 0, 0],
       [0, 1, 0],
       [0, 1, 0],
       [1, 0, 0],
       [1, 0, 0],
       [0, 1, 0],
       [0, 0, 1],
       [0, 1, 0],
       [0, 1, 0],
       [0, 0, 1],
       [0, 0, 1],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 0, 1],
       [1, 0, 0],
       [0, 1, 0],
       [0, 0, 1],
       [1, 0, 0],
       [0, 0, 1],
       [0, 1, 0],
       [1, 0, 0],
       [0, 1, 0],
       [0, 1, 0],
       [1, 0, 0],
       [1, 0, 0],
       [0, 0, 1],
       [0, 0, 1],
       [0, 0, 1],
       [0, 1, 0]], dtype=uint8)

In [32]:
y_test_class = np.argmax(y_test, axis = 1 )

In [34]:
y_pred_class = np.argmax(y_pred, axis = 1 )

In [33]:
y_test_class

array([0, 1, 1, 0, 0, 1, 2, 1, 1, 2, 2, 1, 1, 1, 2, 0, 1, 2, 0, 2, 1, 0,
       1, 1, 0, 0, 2, 2, 2, 1])

In [35]:
y_pred_class

array([0, 1, 1, 0, 0, 1, 2, 1, 2, 2, 2, 1, 1, 1, 2, 0, 1, 2, 0, 1, 1, 0,
       1, 1, 0, 0, 2, 2, 2, 1])

In [37]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [39]:
print(classification_report (y_pred_class, y_test_class))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00         8
           1       0.92      0.92      0.92        13
           2       0.89      0.89      0.89         9

    accuracy                           0.93        30
   macro avg       0.94      0.94      0.94        30
weighted avg       0.93      0.93      0.93        30



In [40]:
print(confusion_matrix (y_pred_class, y_test_class))

[[ 8  0  0]
 [ 0 12  1]
 [ 0  1  8]]


In [41]:
(8+12+8)/30

0.9333333333333333

In [43]:
accuracy_score(y_pred_class, y_test_class)

0.9333333333333333